use std::io::Write;
use std::path::Path;

/// Build script: embeds all `mappings/<version>.tiny.gz` files into the binary
/// via `include_bytes!`. The generated `embedded_mappings.rs` provides
/// `get(version) -> Option<&'static [u8]>`.
fn main() {
    println!("cargo:rerun-if-changed=mappings");

    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let mappings_dir = Path::new(&manifest).join("mappings");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("embedded_mappings.rs");

    let mut entries: Vec<(String, String)> = Vec::new();
    if mappings_dir.is_dir() {
        for entry in std::fs::read_dir(&mappings_dir).unwrap() {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().into_owned();
            if let Some(version) = name.strip_suffix(".tiny.gz") {
                entries.push((escape(version), escape(version)));
            }
        }
    }
    entries.sort();

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs - do not edit\n");
    code.push_str("pub fn get(version: &str) -> Option<&'static [u8]> {\n");
    code.push_str("    match version {\n");
    for (version, file) in entries {
        code.push_str(&format!(
            "        \"{}\" => Some(include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/mappings/{}.tiny.gz\"))),\n",
            version, file
        ));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let mut f = std::fs::File::create(&dest).unwrap();
    f.write_all(code.as_bytes()).unwrap();
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
